apiVersion: v1
kind: Service
metadata:
  name: vite-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"   # Use AWS ALB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # Public ALB
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip" # Targets pods directly
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
 
